METRIC_MAP = {
    # Auth Service Metrics
    "audit_failed_disk_monitoring": "audit.failed_disk_monitoring",
    "audit_failed_emit_events": "audit.failed_emit_events",
    "audit_percentage_disk_space_used": "audit.percentage_disk_space_used",
    "audit_server_open_files": "audit.server_open_files",
    "auth_generate_requests_throttled_total": "auth.generate.requests.throttled.total",
    "auth_generate_requests_total": "auth.generate.requests.total",
    "auth_generate_requests": "auth.generate.requests",
    "auth_generate_seconds": "auth.generate.seconds",
    "backend_batch_read_requests_total": "backend.batch.read.requests.total",
    "backend_batch_read_seconds": "backend.batch.read.seconds",
    "backend_batch_write_requests_total": "backend.batch.write.requests.total",
    "backend_batch_write_seconds": "backend.batch.write.seconds",
    "backend_read_requests_total": "backend.read.requests.total",
    "backend_read_seconds": "backend.read.seconds",
    "backend_requests": "backend.requests",
    "backend_write_requests_total": "backend.write.requests.total",
    "backend_write_seconds": "backend.write.seconds",
    "cluster_name_not_found_total": "cluster_name_not_found.total",
    "dynamo_requests_total": "dynamo.requests.total",
    "dynamo_requests": "dynamo.requests",
    "dynamo_requests_seconds": "dynamo.requests.seconds",
    "etcd_backend_batch_read_requests": "etcd.backend.batch.read.requests",
    "etcd_backend_batch_read_seconds": "etcd.backend.batch.read.seconds",
    "etcd_backend_read_requests": "etcd.backend.read.requests",
    "etcd_backend_read_seconds": "etcd.backend.read.seconds",
    "etcd_backend_tx_requests": "etcd.backend.tx.requests",
    "etcd_backend_tx_seconds": "etcd.backend.tx.seconds",
    "etcd_backend_write_requests": "etcd.backend.write.requests",
    "etcd_backend_write_seconds": "etcd.backend.write.seconds",
    "teleport_etcd_events": "etcd.events",
    "teleport_etcd_event_backpressure": "etcd.event_backpressure",
    "firestore_events_backend_batch_read_requests": "firestore.events.backend.batch.read.requests",
    "firestore_events_backend_batch_read_seconds": "firestore.events.backend.batch.read.seconds",
    "firestore_events_backend_batch_write_requests": "firestore.events.backend.batch.write.requests",
    "firestore_events_backend_batch_write_seconds": "firestore.events.backend.batch.write.seconds",
    "firestore_events_backend_write_requests": "firestore.events.backend.write.requests",
    "firestore_events_backend_write_seconds": "firestore.events.backend.write.seconds",
    "gcs_event_storage_downloads_seconds": "gcs.event_storage.downloads.seconds",
    "gcs_event_storage_downloads": "gcs.event_storage.downloads",
    "gcs_event_storage_uploads_seconds": "gcs.event_storage.uploads.seconds",
    "gcs_event_storage_uploads": "gcs.event_storage.uploads",
    "grpc_server_started_total": "grpc_server.started.total",
    "grpc_server_handled_total": "grpc_server.handled.total",
    "grpc_server_msg_received_total": "grpc_server.msg.received.total",
    "grpc_server_msg_sent_total": "grpc_server.msg.sent.total",
    "heartbeat_connections_received_total": "heartbeat.connections.received.total",
    "s3_requests_total": "s3.requests.total",
    "s3_requests": "s3.requests",
    "s3_requests_seconds": "s3.requests.seconds",
    "teleport_audit_emit_events": "audit.emit.events",
    "teleport_audit_parquetlog_batch_processing_seconds": "audit.parquetlog.batch.processing.seconds",
    "teleport_audit_parquetlog_s3_flush_seconds": "audit.parquetlog.s3.flush.seconds",
    "teleport_audit_parquetlog_delete_events_seconds": "audit.parquetlog.delete.events.seconds",
    "teleport_audit_parquetlog_batch_size": "audit.parquetlog.batch.size",
    "teleport_audit_parquetlog_batch_count": "audit.parquetlog.batch.count",
    "teleport_audit_parquetlog_last_processed_timestamp": "audit.parquetlog.last_processed.timestamp",
    "teleport_audit_parquetlog_age_oldest_processed_message": "audit.parquetlog.age_oldest_processed.message",
    "teleport_audit_parquetlog_errors_from_collect_count": "audit.parquetlog.errors_from_collect.count",
    "teleport_connected_resources": "connected_resources",
    "teleport_registered_servers": "registered_servers",
    "teleport_registered_servers_by_install_methods": "registered_servers.by_install_methods",
    "user_login_total": "user.login.total",
    "teleport_migrations": "migrations",
    "watcher_event_sizes": "watcher.event_sizes",
    "watcher_events": "watcher.events",
    # Proxy Service Metrics
    # Database Service Metrics
    # Kubernetes Access Metrics
    # SSH Service Metrics
    # Kubernetes Service Metrics
    # Common Metrics
}